name: Data Fetcher Pipeline

# トークンに書き込み権限を付与
permissions:
  contents: write

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    # 毎日午前9時(UTC)に実行する場合
    - cron: '0 9 * * *'
  workflow_dispatch:
    # UIから手動実行するためのトリガー

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # ディレクトリ内容を確認
        ls -la
        # 存在確認
        if [ -f "requirements.txt" ]; then
          pip install -r requirements.txt
        else
          # ファイルが無い場合は直接インストール
          pip install pandas requests pytest
        fi
    
    - name: Run tests
      run: |
        pytest test_data_fetcher.py -v
  
  fetch_data:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # ディレクトリ内容を確認
        ls -la
        # 存在確認
        if [ -f "requirements.txt" ]; then
          pip install -r requirements.txt
        else
          # ファイルが無い場合は直接インストール
          pip install pandas requests pytest
        fi
    
    - name: Fetch data
      run: |
        python data_fetcher.py
    
    - name: Commit and push if data changed
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git add data/sample_name.json
        # 変更があった場合のみコミット
        if git diff --staged --quiet; then
          echo "No changes to commit"
        else
          git commit -m "Update data $(date +'%Y-%m-%d')"
          # PAT（Personal Access Token）を使用してプッシュ
          git push "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" HEAD:${GITHUB_REF#refs/heads/}
        fi